# Generated by Django 3.0.8 on 2020-07-16 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_info', '0003_auto_20200714_2258'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='college',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='college_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='tenth_school',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='tenth_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='university',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='university_year',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
