# Generated by Django 3.0.8 on 2020-07-17 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_info', '0005_auto_20200716_1753'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='college_year',
            new_name='Age',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='tenth_year',
            new_name='contact_number',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='college_location',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='college_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='tenth_location',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='tenth_school',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='university_location',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='university_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='university_year',
        ),
        migrations.AddField(
            model_name='profile',
            name='Address',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='Bio',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='Date_of_Birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
