# Generated by Django 3.0.8 on 2020-07-17 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_info', '0006_auto_20200717_1355'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='Address',
        ),
        migrations.AddField(
            model_name='profile',
            name='City',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='Bio',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
