# Generated by Django 3.0.3 on 2020-07-17 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_info', '0008_auto_20200718_0042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorprofile',
            old_name='account',
            new_name='user',
        ),
    ]
