# Generated by Django 3.0.3 on 2020-07-18 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_info', '0011_auto_20200718_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tutorprofile',
            name='location',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='qualification',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='tutorprofile',
            name='subjects',
            field=models.TextField(blank=True, null=True),
        ),
    ]
