# Generated by Django 3.0.3 on 2020-07-18 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profile_info', '0012_auto_20200718_1036'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tutorprofile',
            old_name='account',
            new_name='key',
        ),
    ]
